fixtures
successFixture
	^ '
[1m[34m#############
[1m[34m# Stdout-testReportSuccess#
[1m[34m# 5 Tests with 0 Failures and 0 Errors in s #
[1m[34m#############
[0m
(5 tests passed)
[1m
SCIPassingTests
[0m[32m ✓[0m #testAssert (ms)[0m
[32m ✓[0m #testAssertEquals (ms)[0m
[32m ✓[0m #testDeny (ms)[0m
[32m ✓[0m #testEmpty (ms)[0m
[32m ✓[0m #testRaise (ms)[0m


[1m[32m  Executed 5 Tests with 0 Failures and 0 Errors in s.[0m

'