#!/usr/bin/env bash

set -o errexit
set -o errtrace

if [[ -z "$@" ]]; then
  echo 'Please specify at least a Smalltalk image via the `-s | --smalltalk` option.'
  exit 1
fi

pushd ~/ > /dev/null
if ! ls smalltalkCI-* 1> /dev/null 2>&1; then
  echo "Downloading and extracting smalltalkCI..."
  curl -sSL -o smalltalkCI.tar.gz https://github.com/hpi-swa/smalltalkCI/archive/master.tar.gz
  tar -xzf smalltalkCI.tar.gz
fi
cd smalltalkCI-*
source env_vars
popd > /dev/null

"${SMALLTALK_CI_HOME}/bin/smalltalkci" $@
