constants
lcovEndToEndOutputIn: aDirectory

	^ 'TN:
SF:', aDirectory, SmalltalkCI pathNameDelimiter, 'test.st
DA:1,1
DA:2,1
DA:4,0
LH:2
LF:3
end_of_record
TN:
SF:', aDirectory, SmalltalkCI pathNameDelimiter, 'test2.st
DA:1,1
DA:2,1
LH:2
LF:2
end_of_record
TN:
SF:', aDirectory, SmalltalkCI pathNameDelimiter, 'test3.st
DA:1,0
DA:2,0
LH:0
LF:2
end_of_record
TN:
SF:', aDirectory, SmalltalkCI pathNameDelimiter, 'test4.st
LH:0
LF:0
end_of_record
'